"""duplicate flags and merge tombstones

Revision ID: 2a3bcbb45097
Revises: 26177a12e206
Create Date: 2026-07-12 14:35:22.216661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3bcbb45097'
down_revision: Union[str, None] = '26177a12e206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duplicate_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_a_id', sa.UUID(), nullable=False),
    sa.Column('patient_b_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_a_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['patient_b_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_flags_patient_a_id'), 'duplicate_flags', ['patient_a_id'], unique=False)
    op.create_index(op.f('ix_duplicate_flags_patient_b_id'), 'duplicate_flags', ['patient_b_id'], unique=False)
    op.add_column('patients', sa.Column('merged_into_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'patients', 'patients', ['merged_into_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'merged_into_id')
    op.drop_index(op.f('ix_duplicate_flags_patient_b_id'), table_name='duplicate_flags')
    op.drop_index(op.f('ix_duplicate_flags_patient_a_id'), table_name='duplicate_flags')
    op.drop_table('duplicate_flags')
    # ### end Alembic commands ###
