"""consent grants and restricted flag

Revision ID: 327620d5e05a
Revises: 2a3bcbb45097
Create Date: 2026-07-12 14:44:25.494583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327620d5e05a'
down_revision: Union[str, None] = '2a3bcbb45097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consent_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('grantee_type', sa.String(length=10), nullable=False),
    sa.Column('grantee', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_grants_patient_id'), 'consent_grants', ['patient_id'], unique=False)
    op.add_column('patients', sa.Column('restricted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'restricted')
    op.drop_index(op.f('ix_consent_grants_patient_id'), table_name='consent_grants')
    op.drop_table('consent_grants')
    # ### end Alembic commands ###
