"""sessions revoked cutoff

Revision ID: c13b6e5ba882
Revises: dfeb78fe8323
Create Date: 2026-07-12 18:05:03.279681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c13b6e5ba882'
down_revision: Union[str, None] = 'dfeb78fe8323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sessions_revoked_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sessions_revoked_at')
    # ### end Alembic commands ###
